fixes security vulnerabilities (#462)
* fix: security vunerablilites resolved

* fix(ui): upgarded to angular 8

* fix(database): wait it mongo server get ready

* fix: fix security vulnerabilities reverted as application has to upgrade to suite node version 12

* fix(offchain): truffle-contract module useage removed

* fix(zkp): deprecated module truffle-contract replaced with @truffle/contract

* fix(offchain): eslint fix

* fix: npm run fix executed in repo

* fix(ui): bug at tansaction list tab for ft-commitment resolved

* fix(zkp): truffle-contract module removed and nighlite module upgraded

* fix: github action workflow fixes

* fix: github actions workflow correcting testing

* fix(zkp): package-lock.json is add to .gitignore as auth install of github npm module is causing error while npm ci

* refactor: readme.md file updated with info set env variable NPM_TOKEN

* refactor: implemented different logic to wait database for mongo to get ready

* fix(zkp): compliance unit test cases

* fix: eslint fix

* fix: bug fix

* fix: script to docker-compose instead of docker for mongo container is ready check

* fix: docker-compose exec comand corrected

* fix: github action fix

* fix: testing docker cmd in github actions

* fix: avoid docker-compose exec in github actions

* fix: zkp unit test for compliance setup added to github action workflow

* fix: github action fixes

* fix: downgraded jest version

* fix: eslint fix

* fix: nightlite module upgraded

* fix: nightlite module upgraded

* fix: fixing mongo install in database dockerimage

* fix: commitlint configuration corrected

* fix: husky config fixed

* fix: node version upgraded to 14.15.0

* fix: github actions updated node version 14

* fix: eslint warning removed

* fix: github actions eslint corrected

* fix(github-action): bug fix

* fix: winston downgraded

* fix: nightlite upgraded to resolve winston logger error

* fix: winston package version

* test: winston package version to resolve the bug

* test: winston package version to resolve the bug 2

* fix(ui): tslint issues fixed

* test(ui): this change to resolve angular upgrade from 8 to 9

* test(ui): this change to resolve angular upgrade from 8 to 9 - test 2

* test(ui): this change to resolve angular upgrade from 8 to 9 - test 3

* test(ui): this change to resolve angular upgrade from 8 to 9 - test 4

* fix(ui): upgrade to angular v10 done with correction

* fix(github-action): using npm ci intead of npm i in all  micorservice instead of zkp

diff --git a/nightfall b/nightfall
--- a/nightfall
+++ b/nightfall
@@ -7,7 +7,7 @@ NC='\033[0m'
 
 launchContainers(){
   printf "${GREEN}*** Docker Compose Build ***${NC}\n"
-  docker-compose build
+  docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN}
 
   printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
   docker-compose up -d ganache
@@ -25,7 +25,9 @@ launchContainers(){
   docker-compose up -d mongo-merkle-tree
   docker-compose up -d mongo-nightfall
 
-  sleep 10
+  while ! docker-compose exec mongo-nightfall mongo nightfall --host=localhost -u admin -p admin is-mongo-ready.js; do
+    sleep 3
+  done
 
   printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
   docker-compose up
@@ -62,12 +64,18 @@ cleanup(){
 
 cleanup
 
+if [[ -z "$NPM_TOKEN" ]]; then
+  printf "${RED}*** ENV variable NPM_TOKEN is not set ***${NC}\n"
+  printf "Please set a valid (permission required :repo and :read-packages) github personal access token to the ENV - 'NPM_TOKEN'\n"
+  exit 1
+fi
+
 printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
 docker pull zokrates/zokrates:0.5.1
 
 printf "${GREEN}*** Installing zkp dependencies ***${NC}\n"
 pushd zkp
-npm ci
+npm i
 popd
 
 if [[ "$1" == "compliance" || "$1" == "mimc" ]]
diff --git a/nightfall-test b/nightfall-test
--- a/nightfall-test
+++ b/nightfall-test
@@ -9,7 +9,7 @@ declare isTestFailed=false
 
 launchContainersAndRunIntegrationTest(){
   printf "${GREEN}*** Docker Compose Build ***${NC}\n"
-  docker-compose build
+  docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN}
 
   printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
   docker-compose up -d ganache
@@ -26,7 +26,13 @@ launchContainersAndRunIntegrationTest(){
   docker-compose up -d mongo-merkle-tree
   docker-compose up -d mongo-nightfall
 
-  sleep 10
+  # check to avoid `docker-compose exec` in github actions workflow
+  if [[ ! $GITHUB_ACTION ]]
+  then
+    while ! docker-compose exec mongo-nightfall mongo nightfall --host=localhost -u admin -p admin is-mongo-ready.js; do
+      sleep 3
+    done
+  fi
 
   printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
   if [[ -f docker-compose.override.yml ]]
@@ -75,6 +81,12 @@ cleanup(){
 
 cleanup
 
+if [[ -z "$NPM_TOKEN" ]]; then
+  printf "${RED}*** ENV variable NPM_TOKEN is not set ***${NC}\n"
+  printf "Please set a valid (permission required :repo and :read-packages) github personal access token to the ENV - 'NPM_TOKEN'\n"
+  exit 1
+fi
+
 printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
 docker pull zokrates/zokrates:0.5.1
 
@@ -83,7 +95,7 @@ npm ci
 
 printf "${GREEN}*** Installing zkp dependencies ***${NC}\n"
 pushd zkp
-npm ci
+npm i
 popd
 
 if [[ "$1" == "compliance" || "$1" == "mimc" ]]
